### ISSUE TITLE
Can't compute gradient operator

### ISSUE THREAD

**Issue by FrankFeenix** [Qiskit/qiskit-machine-learning#101]
### Information

- **Qiskit Machine Learning version**: 0.1.0
- **Python version**: 3.8.8
- **Operating system**: Windows 10 Pro

### What is the current behavior?
Failed to try the example of the first Machine Learning Programming Experiment in Qiskit:
Cannot compute gradient operator! Continuing without gradients!

### What is the expected behavior?
Run without issue

>

**Comment by adekusar-drl** [comment]
Can you please share more details?

**Comment by FrankFeenix** [comment]
@adekusar-drl As above, I said installed the library module then tried to try an example on ReadMe but got the same error as above. That is what I want to say

**Comment by adekusar-drl** [comment]
Thanks for noting this. This is not an error, but rather a warning in this case. We use `COBYLA` optimizer in this example, which is gradient free, so the example is still good.

**Comment by moustafa7zada** [comment]
@adekusar-drl 
sorry for bothering ... but the `COBYLA` optimizer still shows the same warnning for me(Cannot compute gradient operator! Continuing without gradients) 
any idea how this may be fixed ?
note: i have the latest version of qisktit

**Comment by adekusar-drl** [comment]
@moustafa7zada In general, it is just a warning, not an error. That means, the code with this warning may still work correctly. Even if you use `COBYLA` you may see this warning. Since `COBYLA` is a gradient free optimizer, it does not require gradient evaluation, hence gradient is not required. Without seeing the code I can't say more about this issue.

**Comment by moustafa7zada** [comment]
@adekusar-drl
thanks a lot for your help :) ..the code looks like this
 `num_qubits = 2      
depth = 4            
theta = ParameterVector('\u03B8', length=num_qubits)  # creating a list of Parameters
custom_circ = QuantumCircuit(num_qubits)

for _ in range(depth) :
    for i in range(num_qubits):
        custom_circ.rx(theta[i], i)
        
    for j in range(num_qubits):
        for k in range(j) :
            custom_circ.cx(k , j)
    custom_circ.barrier()

qc = RawFeatureVector(4)
	my_opt = COBYLA(maxiter=500, tol=0.001)
	vqc = VQC(optimizer=my_opt , feature_map =qc , ansatz = custom_circ )`

**Comment by adekusar-drl** [comment]
@moustafa7zada the reason is `RawFeatureVector`. The model can be trained using gradient free optimizers.

**Comment by moustafa7zada** [comment]
@adekusar-drl Okay i will go with `COBYLA`... thank you for your time.
just one last question . is `COBYLA` the only gradient free optimizer in qiskit?

**Comment by adekusar-drl** [comment]
Explore the package https://qiskit.org/documentation/stubs/qiskit.algorithms.optimizers.html
For instance, `SPSA` is also gradient free. It estimates gradient without direct invocations of the gradient framework. If it is unclear from the documentation, you may query `gradient_support_level`:
```
opt = COBYLA()
opt.gradient_support_level
Out[13]: <OptimizerSupportLevel.ignored: 1>

opt = ADAM()
opt.gradient_support_level
Out[16]: <OptimizerSupportLevel.supported: 2>
```
