### ISSUE TITLE
Indention bug in else statement of torch connector. 

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-machine-learning#105]
### Information

- **Qiskit Machine Learning version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

There is an indentation error on line 166 of the torch connector.

**Comment by adekusar-drl** [comment]
@nonhermitian What is wrong with indentation in this code? Looks good to me.

**Comment by nonhermitian** [comment]
The issue originates from someone other than myself so I cannot say. However it seems that one of the statements is not nested at the correct level and causes issues when actually using the module.

**Comment by adekusar-drl** [comment]
Well, it is supposed to be an `if - elif - else` statement. So, it is unclear where indentation is wrong. Do you have any other details of the issue or know who originally raised this issue?

**Comment by nonhermitian** [comment]
![image](https://user-images.githubusercontent.com/1249193/120317615-dc3bc480-c2ac-11eb-909d-9d2f9641f5c6.jpeg)

Sorry they reported it a bit further down.

**Comment by adekusar-drl** [comment]
I see, the selected part looks good to me either. So, are there any actual problems with the torch connector e.g. wrong results?

**Comment by nonhermitian** [comment]
Please just close this issue. I will ask the original authors to post a new issue themselves.

**Comment by adekusar-drl** [comment]
OK, thanks.
