### ISSUE TITLE
Quantum autoencoder

### ISSUE THREAD

**Issue by frmetz** [Qiskit/qiskit-machine-learning#109]
We have been working on an implementation of a quantum autoencoder as part of the Qiskit Hackathon Europe: Research Study Groups. The quantum autoencoder is based on these two papers:
* https://arxiv.org/abs/1612.02806
* https://arxiv.org/abs/2010.06599

I would be happy to adapt our work so that it could be merged into the qiskit code base, if there is interest in having it included.

I am sorry that this isn’t a proper “feature request” but I wasn’t sure where to ask.

**Comment by adekusar-drl** [comment]
Hi, this is really interesting. Could you please share slightly more information on implementation? Would be nice to see how it looks like, e.g.interfaces you want to implement, and how it can be used, e.g. a use case for it. Also it is important to see how it can be integrated with the with existing framework. I can help with certain things, but definitely should know more about it.

**Comment by frmetz** [comment]
Hi,
Sorry for the late reply, the final week of the hackathon was quite busy!

You can find our current implementation here: [qae.py](https://github.com/Qottmann/Quantum-anomaly-detection/blob/main/qae.py). It contains two classes `QAEAnsatz` (which is a slightly modified version of a `TwoLocal` circuit) and `QAE` (the training framework). The `QAE` is trained in an unsupervised fashion not requiring labeled training data and we currently optimize it using `SPSA`. There are still a few things missing (training on a batch of data, the decoder part, and a feature map), which I will implement the coming days.

Use case: Like a classical neural network based auto-encoder the QAE can be trained to compress classical or quantum data. In our case we employed it to compress ground states of Hamiltonians. This can then be used for anomaly detection and allowed us to map out phase diagrams of the given Hamiltonian. (See our repository [Quantum-anomaly-detection](https://github.com/Qottmann/Quantum-anomaly-detection) for this particular example). However, people have also used it already for compressing digits in the MNIST data set (https://iopscience.iop.org/article/10.1088/2632-2153/ac0616).

I am happy to keep working on it and also implement one of the use case examples including all the documentation. But I would also totally understand if you think the QAE does not fit into this repo. Either way, just let me know!

**Comment by adekusar-drl** [comment]
Hi,

QAE fits perfectly well into this repo and it really looks like a solid contribution. But in this same time you should follow the contribution guidelines, implement the encoder/decoder in the same paradigm as NNs are currently implemented. Please take a look at the `NeuralNetwork` class, this is a base class for all neural networks. Of course, I do not say it is cast in stone, the base class can be extended if some features are missing. As examples of concrete implementations you can take a look at `CircuitQNN` and `OplfowQNN` classes. We expect that new features will follow the framework we introduced. Also, there should be a documentation in place and since this is a big chunk of code and a brand new feature there should be a tutorial as a jupyter notebook. I hope, I did not scare you a lot. Surely, I can help and guide you if you have any questions.

**Comment by adekusar-drl** [comment]
Take a look at the contribution guideline here: https://github.com/Qiskit/qiskit-machine-learning/blob/main/CONTRIBUTING.md

**Comment by frmetz** [comment]
Thank you for the concrete hints! I will start working on it, but it will probably take me a bit until I have it fully integrated into the current framework. If I run into problems, I will ask here. Thanks!

**Comment by adekusar-drl** [comment]
No rush, whenever you have a question, you can post it here.

**Comment by adekusar-drl** [comment]
@frmetz Hi, are there any updates on quantum autoencoder?

**Comment by frmetz** [comment]
Sorry, I am terribly busy at the moment and totally forgot about it. I will make some time as soon as possible and have a look at it again. However, if anyone else wants to implement it, don’t wait for me and go ahead.

**Comment by adekusar-drl** [comment]
OK, thanks for the update. So far we don't have any plans for autoencoders.

**Comment by adekusar-drl** [comment]
@frmetz Closing this issue as an inactive one. You may re-open if you get back to this topic.
