### ISSUE TITLE
Search Function not working in Qiskit Machine Learning 

### ISSUE THREAD

**Issue by divshacker** [Qiskit/qiskit-machine-learning#110]
### Information

- **Qiskit Machine Learning version**: NA
- **Python version**: NA
- **Operating system**: NA

### What is the current behavior?
The Search Function of Qiskit Machine Learning is not working.

### Steps to reproduce the problem
Just go to this https://qiskit.org/documentation/machine-learning/ and type anything you want to search.

### What is the expected behavior?
It will not work as expected.

### Suggested solutions
I think search function have some sort of bug internally and needs to be fixed ASAP

**Comment by adekusar-drl** [comment]
@manoelmarques I guess this issue should be addressed in another repo or CI?

**Comment by manoelmarques** [comment]
@adekusar-drl Similar issue has already been created: Qiskit/qiskit#1223

**Comment by divshacker** [comment]
Is there is any work going on in this issue then ? @manoelmarques ?

**Comment by manoelmarques** [comment]
It possibly involves integrating Google search engine to search all applications. I believe there would be more discussion on this.

**Comment by divshacker** [comment]
Well then I think there is no point in opening this issue now. I am closing this and consider this discussion further on Qiskit/qiskit#1223.

**Comment by adekusar-drl** [comment]
@divshacker I'd suggest to follow up in that issue, to show your interest.
