### ISSUE TITLE
Allow setting an ``initial_point`` in the ``NeuralNetwork``s

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-machine-learning#113]
### What is the expected enhancement?

Should the `NeuralNetwork` algorithms should support passing an ``initial_point`` for the weights? 

It seems that right now this is technically possible by setting `warm_start` to true and setting the private `_fit_result` property, but that's rather hacky 🙂

**Comment by adekusar-drl** [comment]
Oh yes, just hit the same issue. I hope this feature will be in place soon.

**Comment by Cryoris** [comment]
I'll open a PR soon, just need to add some tests 😄

**Comment by adekusar-drl** [comment]
It is done already #115
