### ISSUE TITLE
Leverage fast classical gradients and QFI for statevector simulations

### ISSUE THREAD

**Issue by Cryoris** [Qiskit/qiskit-machine-learning#118]
### What is the expected behavior?

For statevector simulations we can use faster classical evaluation schemes for the gradients, as proposed in https://arxiv.org/abs/2009.02823 and https://arxiv.org/abs/2011.02991. These methods are significantly faster than the current ones as they (1) asymptotically scale with one less power (linear for gradients, quadratic for natural gradients) and (2) have much less overhead from constructing circuits and opflow expressions.

The code for these methods is implemented using Qiskit in https://github.com/Cryoris/surfer. The gradient version works for any circuit, but the QFI code doesn't currently support repeated parameters.

**Comment by Cryoris** [comment]
Update: The classical gradients are implemented for the estimator, as `ReverseEstimatorGradient` and  for the QGT as `ReverseQGT` in Qiskit Terra.

**Comment by adekusar-drl** [comment]
Closing the issue as it is implemented in Terra
