### ISSUE TITLE
Request for translating Qiskit Machine learning tutorials

### ISSUE THREAD

**Issue by starktech23** [Qiskit/qiskit-machine-learning#128]
### What is the expected enhancement?

Qiskit Documentation is currently published in 7 languages (including English). The translation effort is driven by a team of volunteer translators. Now that the tutorials are in separate repository, the team would like to start translating the Machine learning translations which can benefit the community especially during the upcoming Qiskit Summer School, as well is of importance to several of Qiskit's internal teams.

**Comment by adekusar-drl** [comment]
@woodsp-ibm Do you know how we should proceed here?

**Comment by SooluThomas** [comment]
I have opened a PR #130 for addressing this.

**Comment by adekusar-drl** [comment]
@SooluThomas may I close this issue?

**Comment by SooluThomas** [comment]
@adekusar-drl Yes, this is done. Thank you!
