### ISSUE TITLE
Allow measuring subset of qubits when QuantumKernel.evaluate() is run on MPS simulator

### ISSUE THREAD

**Issue by omarshehab** [Qiskit/qiskit-machine-learning#157]
### What is the expected enhancement?
Right now `QuantumKernel.evaluate()` measures all qubits used in the circuit. There should be a way to take advantage of the fix given [here](https://github.com/Qiskit/qiskit-aer/pull/1277) if the MPS simulator is used with the option `"mps_sample_measure_algorithm": "mps_apply_measure"`.

**Comment by woodsp-ibm** [comment]
From the link this looks like a performance enhancement when using MPS simulator when all qubits are being measured. You can pass in an Aer simulator set for MPS mode and configure it accordingly. Having only just skimmed over the PR you linked what is it that you are proposing is changed here? 

As far as the title is concerned `Allow measuring subset of qubits` - I got the impression from reading the linked PR that the change did not cater to that, but it might be possible to do later. Can you explain further...

**Comment by omarshehab** [comment]
@woodsp-ibm , The `QuantumKernel.evaluate()` API currently measures all qubits so we cannot take advantage of measuring subset of qubits when we are using the MPS simulator.

**Comment by woodsp-ibm** [comment]
I guess I am confused - the PR you linked says this as a summary

> Performance improvement for the case where all qubits are measured.

and later

> It is possible to implement for cases where a subset of the qubits is measured, but this will require additional effort to decide when propagation is necessary and when not.

which I took to mean that it was not implemented at present anyway.

**Comment by omarshehab** [comment]
@woodsp-ibm , it has been implemented and merged as shown below.

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/4205827/125351447-18dbf080-e32e-11eb-877c-dc8ce03853c1.png">

Unfortunately,` QuantumKernel.evaluate()`, while running on MPS simulator, cannot take advantage of this at this moment.

**Comment by adekusar-drl** [comment]
@omarshehab Could you please write a bit detailed description? I don't fully understand what is suggested to do here.

**Comment by adekusar-drl** [comment]
As I see in `qiskit_machine_learning.kernels.QuantumKernel` implementation, only a required number of qubits is measured, basically it is the number of qubits in the feature map passed to `QuantumKernel`. If you don't pass a feature map, then `ZZFeatureMap(2)` is used. So, that's why I don't fully understand what is wrong in the implementation.

By the way, aqua and ` qiskit.aqua.algorithms.VQC` are deprecated, I don't think we will update them with new features.

**Comment by adekusar-drl** [comment]
I'm closing this issue as stale and unclear. Feel free to re-open with more details provided.
