### ISSUE TITLE
Torchconnector fails in backward prop

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-machine-learning#175]
In the backward propagation this code checks `input_grad` and if _not_ None under certain a condition sets it to None

https://github.com/Qiskit/qiskit-machine-learning/blob/00831061ca0206af42e131fcb9b605c4acd404fa/qiskit_machine_learning/connectors/torch_connector.py#L158-L160

later in the same method it makes this call

https://github.com/Qiskit/qiskit-machine-learning/blob/00831061ca0206af42e131fcb9b605c4acd404fa/qiskit_machine_learning/connectors/torch_connector.py#L178

which fails inside Torch einsum util with a complaint about NoneType (which seems to be about input_grad being None)

Similar logic is in the `weight_grad` part too.

I will note that the above logic path, where input_grad is set to None, is not covered by unit tests and so this failure does not arise there.

**Comment by adekusar-drl** [comment]
@woodsp-ibm Interesting, this may happen if `input_grad.shape` has a zero element. A solution off the top of my head is just to add an additional `if input_grad is not None` before the einsum, but I'm not sure. Is there a test case to reproduce the issue?

**Comment by woodsp-ibm** [comment]
Indeed doing the einsum conditionally like that, which is how the failure was avoided so further progress could be made, but since it changed input_grad to None, which is then what is returned, I was not so sure. I don't have a small test case at present but I can see if I can get something even the failing code itself.

**Comment by IceKhan13** [comment]
I think, those cases should be handled in `NeuralNetwork` validate methods (validate inputs, weights and backwards).

https://github.com/Qiskit/qiskit-machine-learning/blob/00831061ca0206af42e131fcb9b605c4acd404fa/qiskit_machine_learning/neural_networks/neural_network.py#L217-L223

Looks like something is zeroing one of the dims in implementation of `_backward`. 

I can look at it

**Comment by adekusar-drl** [comment]
@IceKhan13 Sure, you can take a look.
