### ISSUE TITLE
Fix randomization in the tutorials

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#194]
### What is the expected enhancement?
Currently, Qiskit Machine Learning tutorials use random number generator for various purposes, usually for generating datasets. This request aims at reviewing the tutorials and fixing a seed in the generator for reproducibility purposes.

**Comment by woodsp-ibm** [comment]
@adekusar-drl In unit testing, other potentially random influences come from the simulator, e.g. random sampling for the shots. Also some transpilers have random aspect to their optimization pass - as such seed_simulator and seed_transpiler are also possible. Clearly though these are supposed to be a bit more like a real-world application than a unit test, but having them reproduce the same output should a user a choose to run them gives the user confidence that things are right. Maybe neither of these seeds are needed and simply fixing randomness of any input data, initial points etc suffices, after all I guess based on shot noise users might expect to see differences which would not then be the case if the simulator seed we set.

**Comment by adekusar-drl** [comment]
@woodsp-ibm Main idea here is to have same datasets across multiple runs and since we plot them, then, I think, it is nice to have same plots/numbers every time we run the tutorials. Of course, we can extend the issue to cover other things and other seeds, like you said in transpiler, but, I guess, it can be done later when we fix the tests.

**Comment by woodsp-ibm** [comment]
Ok, since the simulator will have shot noise when not using the statevector, I saw the qasm sim being used, but did not check which output/plots exactly came from it. Just noting that things may look a little because of that.
