### ISSUE TITLE
Add title images to the tutorials

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#196]
### What is the expected enhancement?
Tutorials posted on the QML documentation page, https://qiskit.org/documentation/machine-learning/tutorials/index.html, may have a title image, e.g. the qGANs and Quantum Kernel tutorials have such images, while other tutorials do not. See the screenshot:
![image](https://user-images.githubusercontent.com/62334182/130815704-6421b720-ea2c-450f-9bdc-6a73e21f5aa9.png)

To make the page look better I suggest to add title images to other three tutorials:

- Quantum Neural Networks: to be decided/chosen.
- Neural Network Classifier & Regressor: a classification image.
- TorchConnector: likely an MNIST image should be good.

Images can be added by tagging a cell. A sphinx thumbnail tag in a tutorial cell that produces a figure must be set. If you enable View / Cell Toolbar / Tags you should see it in the above mentioned tutorials as an example.

**Comment by YumaNK** [comment]
Hi! I would like to begin contributing Qiskit Machine Learning from this issue!

**Comment by adekusar-drl** [comment]
Hi! Sure, you can do this.

**Comment by YumaNK** [comment]
I sent pull request.
https://github.com/Qiskit/qiskit-machine-learning/pull/210
