### ISSUE TITLE
Computer vision?

### ISSUE THREAD

**Issue by yogeshriyat** [Qiskit/qiskit-machine-learning#249]
Hello - this is more of a question:

I am working on a computer vision multi-label classification project, and I am wondering if I can train it also with quantum neural nets? If so, does anyone have a tutorial where they have demonstrated this? 

Also, do you guys have a Slack community or something like that where this type of question would be more appropriate? 

Thanks in advance,
Yogesh

**Comment by adekusar-drl** [comment]
@yogeshriyat If you don't have other questions, would you mind closing the issue?
