### ISSUE TITLE
Gradient calculations in some optimizers are invalid

### ISSUE THREAD

**Issue by beyond997** [Qiskit/qiskit-machine-learning#271]
### Environment

- **Qiskit Machine Learning version**:0.2.1
- **Python version**: 3.8.5
- **Operating system**: linux

### What is happening?

I found that most optimizers such as GradientDescent and SciPyOptimizer, define the function _gradient_num_diff_  to estimate the gradient. AQGD defines __compute_objective_fn_and_gradient_ to calculate the analytical gradient.

In fact, when running VQC, it will calculate the gradient through _class VQC (NeuralNetworkClassifier)_ and pass gradient to _optimizer.optimize()_ as a parameter. This will cause the gradient solving function defined in the optimizer to not be used.

I'm not sure in which way VQC calculates the gradient (whether it is related to numerical differentiation), but at least for AQGD, the gradient of VQC is not an analytical gradient. Then the optimizer AQGD is meaningless.

### How can we reproduce the issue?

When I run VQC， 
in qiskit_machine_learning/algorithms/classifiers/neural_network_classifier.py,  _function.gradient_ gives the gradient.

        function = BinaryObjectiveFunction(X, y, self._neural_network, self._loss)
        else:
            if self._one_hot:
                function = OneHotObjectiveFunction(X, y, self._neural_network, self._loss)
            else:
                function = MultiClassObjectiveFunction(X, y, self._neural_network, self._loss)

        objective = self._get_objective(function)

        self._fit_result = self._optimizer.optimize(
            self._neural_network.num_weights,
            objective,
            function.gradient,
            initial_point=self._choose_initial_point(),
            **kwargs
---------------------------------------------------------------------------------------------------------------------------------------------
Below we find the _AQGD.optimize_，
![image](https://user-images.githubusercontent.com/87456331/145393586-9d88197b-64d4-4fb8-8ee3-65d8b4c5da1b.png)
![image](https://user-images.githubusercontent.com/87456331/145393683-4d025204-50c4-4346-b77d-3160521921ec.png)

The gradient calculated by VQC is used as the third parameter of _minimize_
Therefore, in the code will execute
![image](https://user-images.githubusercontent.com/87456331/145394157-4c949c51-8ed6-4c7a-b80d-846aeedb57b8.png)
 
Other optimizers such as SLSQP, CG, L_BFGS_B  also have this problem.

### What should happen?

The gradient calculation defined in the optimizer is not used.

The gradient is always calculated by the following algorithm：
 
from /qiskit_machine_learning/algorithms/objective_functions.py

        def gradient(self, weights: np.ndarray) -> np.ndarray:
              # predict is of shape (N, num_outputs)
              y_predict = self._neural_network_forward(weights)
              # weight probability gradient is of shape (N, num_outputs, num_weights)
              _, weight_prob_grad = self._neural_network.backward(self._X, weights)

              grad = np.zeros(self._neural_network.num_weights)
              num_outputs = self._neural_network.output_shape[0]
              # loss gradient is of shape (N, num_output)
              loss_gradient = self._loss.gradient(y_predict, self._y)
              for i in range(num_outputs):
                  # a dot product(matmul) of loss gradient and weight probability gradient across all
                  # samples for an output.
                  grad += loss_gradient[:, i] @ weight_prob_grad[:, i, :]
  
              return grad
My level is limited, I don’t understand which method is calculating the gradient, I hope you can guide me.

**Comment by adekusar-drl** [comment]
Hello,

I'm not quite sure, I understand the issue. We provide an objective function and a function that computes gradient of the objective and we pass both of them to the optimizer. So, I don't see any issues here.

The way how optimizers are called was changed slightly, as well the optimizer interface. Please take a look at the lines in `NeuralNetworkClassifier`: https://github.com/Qiskit/qiskit-machine-learning/blob/main/qiskit_machine_learning/algorithms/classifiers/neural_network_classifier.py#L105-L112

**Comment by beyond997** [comment]
Thank you for your response @adekusar-drl 
I am new to quantum machine learning, so my understanding is rather shallow. I'm sorry if my description for the issue is a bit confusing. I just can't understand if _NeuralNetworkClassifier_ passes the gradient to the optimizer, then the function defined in the optimizer to calculate the gradient will not be called. 

The key is that, for example, since AQGD uses analytic gradient for optimization, it needs to use the parameter shift rule to calculate gradients(_AQGD._compute_objective_fn_and_gradient_ is defined to calculate analytic gradient based on the parameter shift rule).  So whether the gradient given by _NeuralNetworkClassifier_  is the exact analytic gradient?

There are other optimizers that calculate gradients based on numerical differentiation, is the gradient given by _NeuralNetworkClassifier_ again a numerical differentiation approximation solution? Is this a contradiction? Because no matter which optimizer of gradient calculation rules is used, the gradients are all calculated and passed through _NeuralNetworkClassifier_.

I don't quite understand in what way  _NeuralNetworkClassifier_ calculates the gradient. In the code it looks a bit like _back -propagation_. Could you please explain it for me?Thanks a lot.

**Comment by adekusar-drl** [comment]
> Thank you for your response @adekusar-drl I am new to quantum machine learning, so my understanding is rather shallow. I'm sorry if my description for the issue is a bit confusing. I just can't understand if _NeuralNetworkClassifier_ passes the gradient to the optimizer, then the function defined in the optimizer to calculate the gradient will not be called.

That's right.

> 
> The key is that, for example, since AQGD uses analytic gradient for optimization, it needs to use the parameter shift rule to calculate gradients(_AQGD._compute_objective_fn_and_gradient_ is defined to calculate analytic gradient based on the parameter shift rule). So whether the gradient given by _NeuralNetworkClassifier_ is the exact analytic gradient?

Yes, by default we pass a function that computes exact gradient via the param shift rule.

> 
> There are other optimizers that calculate gradients based on numerical differentiation, is the gradient given by _NeuralNetworkClassifier_ again a numerical differentiation approximation solution? Is this a contradiction? Because no matter which optimizer of gradient calculation rules is used, the gradients are all calculated and passed through _NeuralNetworkClassifier_.
> 

An optimizer does not have to estimate gradients anyhow. It may fully rely on the functions passed to it. And since we don't have any assumptions here, we manually construct a gradient function. The way how an optimizer estimates gradients may be inefficient, so if one can build a gradient function, I think, it is better to do this unless it is proven that the optimizer does it better for some reasons.

> I don't quite understand in what way _NeuralNetworkClassifier_ calculates the gradient. In the code it looks a bit like _back -propagation_. Could you please explain it for me?Thanks a lot.

This is correct, this is backward pass where gradients are computed and the algorithm makes an optimization step.

**Comment by beyond997** [comment]
Thank you for your detailed answer。 @adekusar-drl I have understood your explanation and it is a great help for me. Thanks again.
