### ISSUE TITLE
Is there GPU support for qiskit-machine-learning?

### ISSUE THREAD

**Issue by andb0t** [Qiskit/qiskit-machine-learning#286]
### What is the expected enhancement?

Hi there,

I see `qiskit-aer` providing GPU support via `qiskit-aer-gpu`, can this repo do the same? I'm not into the details, but I suspect there must be some advantage?

Cheers!

**Comment by adekusar-drl** [comment]
We don't have explicit support for GPU. Algorithms in this repo rely in `qiskit-aer` if they are run on a simulator. Thus they may indirectly benefit from such a support. But, I admit, this is a topic that should be explored in more details.

**Comment by adekusar-drl** [comment]
I had a look at the GPU support in Qiskit Aer. If you have GPU support installed for Aer, then you can create a simulator that runs on a GPU like this:
```
simulator_gpu = Aer.get_backend('aer_simulator')
simulator_gpu.set_options(device='GPU')
```
Once you created the simulator, you can create a `QuantumInstance` for this simulator:
```
qi = QuantumInstance(backend=simulator_gpu)
```
And basically you are done. Everything algorithm you run on this quantum instance will run circuits on GPU. So right now there's no need to do anything special to add support of GPU in QML.
Does this answer your question?

**Comment by andb0t** [comment]
It does answer it, thank you!

**Comment by andb0t** [comment]
Basically for most cases, even installing `pip install qiskit-aer-gpu` should suffice, or not?

**Comment by adekusar-drl** [comment]
Yes, you have to install `qiskit-aer-gpu` first then instantiate a simulator with GPU support enabled manually and pass it to a quantum instance. That's it.

**Comment by adekusar-drl** [comment]
@andb0t Do you need more info or I can close the issue?

**Comment by andb0t** [comment]
Thanks! Closing the issue now.
