### ISSUE TITLE
Warn when fitting new data with a different number of classes 

### ISSUE THREAD

**Issue by declanmillar** [Qiskit/qiskit-machine-learning#322]
### What is the expected enhancement?

One can train VQC in batches using the warm_start=True flag. If one then provides data with a different number of total classes, the code will process the data using the initial_point reached in the previous batch without complaint.

While certainly not critical, it might be friendly to warn the user that the data they are providing probably invalidates the parameters reached during the previous fit.

**Comment by adekusar-drl** [comment]
Can you please explain the issue better or give an example?

**Comment by declanmillar** [comment]
Yes, sorry. So, in the example below, the two problems have a different number of target classes. I may be wrong, but I think these problems are incompatible as this is not an online ML algorithm. I don't think this is very important, as users are unlikely to try to fit unrelated datasets in batches to the same model, but we could warn users that these batches are effectively incompatible.

I'm happy to close this issue, as it's not necessary, it was just something that occurred to me while playing around with VQC.

```python
import numpy as np

from qiskit.utils import QuantumInstance
from qiskit_machine_learning.algorithms.classifiers import VQC
from qiskit import Aer

from sklearn.ensemble import RandomForestClassifier

# Choose a seed for the quantum instance initialisation.
seed = 123

# Construct toy data set.
data = np.random.rand(15, 4)
target = np.asarray([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

data2 = np.random.rand(15, 4)
target2 = np.asarray([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

# Onehot encode target1.
onehot_target = np.zeros((target.size, int(target.max() + 1)))
onehot_target[np.arange(target.size), target.astype(int)] = 1

# Onehot encode target2.
onehot_target2 = np.zeros((target2.size, int(target2.max() + 1)))
onehot_target2[np.arange(target2.size), target2.astype(int)] = 1

# Initialise the VQC.
backend = Aer.get_backend("aer_simulator_statevector")
qin = QuantumInstance(backend, seed_simulator=seed, seed_transpiler=seed)
vqc = VQC(
    num_qubits=4,
    feature_map=None,
    ansatz=None,
    loss="cross_entropy",
    optimizer=None,
    warm_start=True,
    quantum_instance=qin,
    initial_point=None,
    callback=None,
)

# Fit the VQC to the constructed toy data
vqc.fit(data, onehot_target)
vqc.fit(data2, onehot_target2)
```

**Comment by adekusar-drl** [comment]
Thanks, makes sense to raise a warning in this case.
