### ISSUE TITLE
Simplify VQC unit tests

### ISSUE THREAD

**Issue by declanmillar** [Qiskit/qiskit-machine-learning#325]
### What is the expected enhancement?

Currently, the VQC unit tests use the DDT library to pass a combination of strings to tests in order to check execution with a range of optimizers and quantum instances. Rather than using string tags, it is possible to pass this data directly, which may minimize and, perhaps, clarify the necessary code for tests.

**Comment by adekusar-drl** [comment]
Perhaps, not only `VQC` tests, but other unit tests as well :)
