### ISSUE TITLE
Introduce an API for saving/loading ML models

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#326]
### What should we add?

Currently there's no native support for saving and loading trained QNN based models. Users can only rely on standard python packages like `pickle` for such tasks and other hacks like saving the `_fit_result` property. Similar questions about saving and loading models were asked a few times on the public Slack workspace. This issue is to tackle this problem. While the problem may (not) sound as an easy one, the implementation may take some time cause an investigation is required first. The problem does not require exhaustive knowledge of quantum computing, so it may be suitable for the first time contributors.

What should be done:

- [ ] Check if a model can be saved/restored via `pickle`. Definitely, it can be done, but what else should be taken care of once a model is loaded is a unclear now. At least a `QuantumInstance` should be set, I guess.
- [ ] Investigate options for the load/save API.
- [ ] Implement the load/save API.

**Comment by prakharb10** [comment]
Hello @adekusar-drl 
After a cursory reading of the `pickle` module, I feel that implementing the `__getstate__()` and `__setstate__()` methods properly should be sufficient to load and save models.
The NeuralNetwork base class or other base classes may introduce an additional `save` method which will allow us to use methods exposed by `pickle` and provide a way to save all models extending from the class.

**Comment by adekusar-drl** [comment]
Thanks for looking into this. In general, may be `pickle` works out of box and double underscore methods are not required, I don't know. More important is that when a model is loaded it has to has a quantum instance. When and how this should be done is a open question. May be introducing a method like `load(file_name, quantum_instance)` is a good choice.

**Comment by andb0t** [comment]
Hi there,
I just hit a wall with exactly this problem. After successfully training my model, I'd like to pickle it to ship it to a server and run it there. Here's what I do:
```python
    filename = 'outputs/model.pkl'
    pickle.dump(model, open(filename, 'wb'))
```
and this is the error I get:
```shell
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    main()
  File "train.py", line 215, in main
    save_model(model)
  File "train.py", line 179, in save_model
    pickle.dump(model, open(filename, 'wb'))
AttributeError: Can't pickle local object 'SummedOp.__init__.<locals>.<lambda>'
```
This answers the question at least if it currently works: it doesn't. Do you think simply replacing lambda functions by named functions, e.g. this one:
```python
        # from file qiskit_machine_learning/neural_networks/circuit_qnn.py: 334
        self._interpret = interpret if interpret is not None else lambda x: x
```
would help?

**Comment by adekusar-drl** [comment]
No, I don't think so. Opflow objects are not pickleable. Replace `pickle` with `dill`. We use `dill` in this new API to save/load models.

**Comment by andb0t** [comment]
That worked. Thanks!
