### ISSUE TITLE
Add Effective Dimension Runtime Client

### ISSUE THREAD

**Issue by ElePT** [Qiskit/qiskit-machine-learning#341]
### What should we add?

The goal of this issue is to track the development of the client for the effective dimension runtime program (also under development), as described in epic https://github.com/Qiskit/qiskit-machine-learning/issues/318. The latest progress on this issue can be found in my personal fork:  https://github.com/ElePT/qiskit-machine-learning/tree/eff-dim, under `qiskit_machine_learnig/runtime`

**Comment by woodsp-ibm** [comment]
Although the title is given as `Effective Dimension Runtime Program` this will just add the Client here right - the server side Program being elsewhere.

**Comment by adekusar-drl** [comment]
Runtimes are being replaced with `Session`. See https://github.com/Qiskit/qiskit-ibm-runtime/ for more details.
