### ISSUE TITLE
Hardcoded test size in breast cancer and digits dataset

### ISSUE THREAD

**Issue by bopardikarsoham** [Qiskit/qiskit-machine-learning#371]
### Environment

-

### What is happening?

test_size being hardcoded to 0.3 in [#Line36](https://github.com/Qiskit/qiskit-machine-learning/blob/main/qiskit_machine_learning/datasets/breast_cancer.py#L36) is not giving the user the flexibility to set the desirable train-test-split ratio.

### How can we reproduce the issue?

The variable `test_size` is already present as an input in the function's parameters. As a result, replacing 0.3 with test_size resolves the problem. 
`sample_train, sample_test, label_train, label_test = train_test_split(
        data, target, test_size=test_size, random_state=12
    )`

### What should happen?

-

### Any suggestions?

I also believe that the random_state variable should be defined as a function parameter. So that the user has the option of randomizing the samplings.

**Comment by adekusar-drl** [comment]
The datasets are deprecated and will be removed in the release after the upcoming `0.4` release. 

The `test_size` variable is used to subset test data here: https://github.com/Qiskit/qiskit-machine-learning/blob/main/qiskit_machine_learning/datasets/breast_cancer.py#L61

**Comment by adekusar-drl** [comment]
I close the issue since these datasets will be removed soon.
