### ISSUE TITLE
QSVM Feature map

### ISSUE THREAD

**Issue by toncho11** [Qiskit/qiskit-machine-learning#382]
Hi,

I have question about QSVM. I did not know where to post it. Please be so kind to have a look at my question before closing it. 

QSVM is using the QunatumKernel class which is using a Quantum Feature Map (implemented as a Quantum circuit).
So what really happens is that Feature Space (the higher dimensional space) is indeed constructed and used to transform the training data to a linearly separable space. So it is a kernel without the "kernel trick" or something like that?

Thanks.

**Comment by adekusar-drl** [comment]
@toncho11 If I understand your question correctly, you described exactly the classical kernel trick. This is what is implemented in `QuantumKernel`, you have just another kernel function that is evaluated on a quantum computer. In this is case your classical data is mapped to Hilbert space and an overlap between two vectors is evaluated.

**Comment by toncho11** [comment]
Here is the confusion:

It seems "Feature Map" is broadly used term.

* "Feature Mapping" is mapping to a higher dimensional space where we can separate the data.
* "Quantum Feature Mapping" is 
  - encoding of classical data to quantum states
  - mapping to Hilbert space 

So is it the same ?

From the [documentation](https://qiskit.org/documentation/stubs/qiskit.circuit.library.ZZFeatureMap.html) of  it is not obvious what is it indeed except that is a Quantum circuit.

**Comment by adekusar-drl** [comment]
Yes, that's right, but even in a higher dimensional space data separation is not guaranteed.

**Comment by toncho11** [comment]
Thanks. So it is the same as in SVM, but with added Quantum circuit mapping.

**Comment by adekusar-drl** [comment]
Yes, for instance, `QSVC` is a wrapper of the classical SVC, can be initialized with a `QuantumKernel` and the latter is a quantum kernel function.

**Comment by toncho11** [comment]
Actually I am preparing a presentation on the topic and that is why I want to be sure how it works. 

And the QSVC in emulation mode uses a normal kernel from ScikiLearn, right?
Because that will be much faster compared to emulating a Quantum kernel on a conventional laptop?

**Comment by adekusar-drl** [comment]
`QSVC` takes an instance of `QuantumKernel` as a kernel function and then fits a model using this kernel function. `QuantumKernel` can be executed either on a simulator or on a real hardware. You can ping me in the public [Qiskit Slack](https://qiskit.slack.com/?redir=%2Fmessages%2FC7SN3T90V) if you want to chat more.

**Comment by adekusar-drl** [comment]
@toncho11 is there anything left here? May I close the issue?

**Comment by toncho11** [comment]
Hi,

Almost. 
I could not log into Qiskit Slack? Do I need some invitation or authorization?

**Comment by adekusar-drl** [comment]
I think you need to create a Slack account or log in using Google/Apple, there are invitations, this is public, as far as I know.

**Comment by toncho11** [comment]
I tried 100 times and ... it does not work without an invitation. 
Please send me an invitation on my github user and @gmail.com

**Comment by adekusar-drl** [comment]
I tried to add you to the workspace, but as far I know, there are no specific requirements to join.

**Comment by toncho11** [comment]
Thanks! Finally it worked.
