### ISSUE TITLE
algorithms_globals

### ISSUE THREAD

**Issue by assad-ua** [Qiskit/qiskit-machine-learning#39]
Hello,
i am not being able to import algorithms_globals.

Any suggestions??

**Comment by woodsp-ibm** [comment]
What version of qiskit do you have installed? What is the error you are getting - is it from code here or from your own code? Please provide more information.

**Comment by manoelmarques** [comment]
The name is algorithm_globals not algorithms_globals. The installed qiskit-terra should be 0.17.0.
```
from qiskit.utils import algorithm_globals
```

**Comment by woodsp-ibm** [comment]
Closing as answered. If however you still have an issue with this not working then feel free to re-open this, providing information and a small code sample etc

**Comment by assad-ua** [comment]
The issue was resolved. Thanks alot.
