### ISSUE TITLE
RawReatureVector - update parameters wrt ordering

### ISSUE THREAD

**Issue by woodsp-ibm** [Qiskit/qiskit-machine-learning#4]
Parameters in Terra QuantumCIrcuit are now ordered. N-Local was updated to remove ordered_parameters as its no longer needed. This library circuit should be updated in a consistent manner (no need to deprecate here though, just remove, since this repo/pkg is new)

NLocal change as reference Qiskit/qiskit-terra#5949 (also see Qiskit/qiskit-terra#5759)

**Comment by Cryoris** [comment]
Fixed via #21.
