### ISSUE TITLE
Quantum CNN

### ISSUE THREAD

**Issue by Gopal-Dahale** [Qiskit/qiskit-machine-learning#408]
### What should we add?

I wanted to contribute a new tutorial on Quantum CNN using Pytorch Lightning. I am following [this ](https://www.tensorflow.org/quantum/tutorials/qcnn) approach using jupyter notebooks. 

The implementation uses `sklearn` `'blobs` dataset to perform binary classification of 2-dimensional data points. It features Quantum convolution and pooling layers. Shall I create a pull request for this?

**Comment by dlasecki** [comment]
Hi, we already have code written with Qiskit for generating quantum circuits for the exact same tutorial referenced. But it is not published anywhere. Let think what's the best way to proceed.

**Comment by adekusar-drl** [comment]
@dlasecki I'd love see some progress on this topic, I don't have time to work on this on my own or in a collaboration with anybody.

**Comment by Gopal-Dahale** [comment]
@dlasecki I tried to follow the code of the referenced tutorial in qiskit and used TorchConnector to train it, but the model does not seem to converge and it takes a lot of time to finish even a single epoch. Using GPU is not beneficial as the number of samples are less (~100) and even when I used GPU the per cent utilization was negligible.

In the torch connector [tutorial](https://qiskit.org/documentation/machine-learning/tutorials/05_torch_connector.html), the authors use only 2 qubits when here using 16 qubits (images resized to 4 x 4) is taking quite a time.

**Comment by adekusar-drl** [comment]
@Gopal-Dahale may we help somehow?

**Comment by dlasecki** [comment]
> @dlasecki I tried to follow the code of the referenced tutorial in qiskit and used TorchConnector to train it, but the model does not seem to converge and it takes a lot of time to finish even a single epoch. Using GPU is not beneficial as the number of samples are less (~100) and even when I used GPU the per cent utilization was negligible.
> 
> 
> 
> In the torch connector [tutorial](https://qiskit.org/documentation/machine-learning/tutorials/05_torch_connector.html), the authors use only 2 qubits when here using 16 qubits (images resized to 4 x 4) is taking quite a time.

Hi, if your code is in a good shape for us to follow, you might open a *draft* PR and we might have a look. Perhaps some things could be optimized or improved.

**Comment by adekusar-drl** [comment]
Closed in #462
