### ISSUE TITLE
Missing instructions for building documentation locally

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-machine-learning#413]
### What is the expected enhancement?

We should add instructions for building documentation locally for contributors who want to contribute on (non jupyter notebook) documentation such as doc string and .rst files.

**Comment by HuangJunye** [comment]
Something like that with more explanations

```bash
# create a new virtual environment and install pip
conda create -n qiskit-ml-dev pip
# activate virtual environment
conda activate qiskit-ml-dev
# install python dependency
pip install -r requirements-dev.txt
pip install -r requirements.txt
# install non-python dependency
conda install pandoc
# build doc
cd docs/
sphinx-build -b html . _build
# open index page with your browser
open _build/index.html
```

**Comment by adekusar-drl** [comment]
@HuangJunye what about a command like `make html`? It builds the documentation.

**Comment by HuangJunye** [comment]
Nice. I didn't know the doc building is added to the Makerfile: https://github.com/Qiskit/qiskit-machine-learning/blob/3e1ed39e3f4d9b650db181866b6d12865a496613/Makefile#L69-L70

But I assume the dependency installation will still be needed.

**Comment by HuangJunye** [comment]
I think pandoc is also needed which is not a python dependency and therefore cannot be pip installed. 

I also didn't look at the https://github.com/Qiskit/qiskit-machine-learning/blob/main/CONTRIBUTING.md#pull-request-checklist which did mention documentation. 

I think we should add pandoc installation to this step and then it should be good. But I haven't verified myself that pandco installation is indeed missing if we follow the steps in CONTRIBUTING.md.

**Comment by HuangJunye** [comment]
@Guillermo-Mijares-Vilarino is our new intern for the documentation. Guillermo, can you try to follow the steps on https://github.com/Qiskit/qiskit-machine-learning/blob/main/CONTRIBUTING.md to do a local build to check if there is any missing steps (for example installing `pandoc`)? Thank you!

**Comment by adekusar-drl** [comment]
Surely, such a check is really appreciated!

**Comment by Guillermo-Mijares-Vilarino** [comment]
I could do the local build writing `make html` when on the docs folder of the qiskit-machine-learning (cloned) repo as the contributing guideline https://github.com/Qiskit/qiskit-machine-learning/blob/main/CONTRIBUTING.md indicated and it worked just fine.

However I had already installed `pandoc` so I tried removing it and redoing the local build. This time I got the following error:

```Notebook error:
PandocMissing in tutorials/01_neural_networks.ipynb:
Pandoc wasn't found.
Please check that pandoc is installed:
https://pandoc.org/installing.html
make: *** [html] Error 2
```



So `pandoc` is needed here.

**Comment by manoelmarques** [comment]
Yes, `pandoc` is needed but is not a python library, in is native. In the MacOS you install with "brew install pandoc".

**Comment by adekusar-drl** [comment]
@manoelmarques Thanks for the clarification. Is it stated somewhere in the documentation that if I want to build documentation manually I have to have `pandoc` installed? I don't think so, at least I have not found `pandoc` in this repo except in the CI stuff. I guess, this is the main point of this issue.

**Comment by HuangJunye** [comment]
@manoelmarques @adekusar-drl Thanks for working on the issue!
