### ISSUE TITLE
PegasosQSVC predicted labels inverted on simple test

### ISSUE THREAD

**Issue by gcattan** [Qiskit/qiskit-machine-learning#447]
### Environment

- **Qiskit Machine Learning version**: 0.4.0
- **Python version**:  3.7, 3.8
- **Operating system**: ubuntu/windows/mac os

### What is happening?

1) Predicted labels are inverted as compared to true labels
![image](https://user-images.githubusercontent.com/6229031/183289339-51ca2ef9-0f1d-4759-9c28-4f4d87c7cf19.png)

2) Sometimes fails with QiskitError:

![image](https://user-images.githubusercontent.com/6229031/183289305-6c70c391-ab13-4c26-8f09-86c00970a578.png)

### How can we reproduce the issue?

```python
import numpy as np
from qiskit import BasicAer
from qiskit_machine_learning.algorithms import PegasosQSVC
from qiskit_machine_learning.kernels.quantum_kernel import QuantumKernel
from qiskit import BasicAer

n_samples, n_features = 10, 4
feat_0 = np.zeros((n_samples, n_features))
feat_1 =  np.ones((n_samples, n_features))
feats = np.concatenate((feat_0, feat_1))
labels = np.concatenate(([0] * n_samples, [1] * n_samples))

backend = BasicAer.get_backend('qasm_simulator')
quantum_kernel = QuantumKernel(quantum_instance=backend)
clf = PegasosQSVC(quantum_kernel=quantum_kernel)

clf.fit(feats, labels)
predicted = clf.predict(feats)
print(predicted, labels)
```

### What should happen?

Predicted labels should be equal to true labels.

**Comment by adekusar-drl** [comment]
Thanks for reporting this issue. The problem with identical samples, and this is what you have in your dataset, is fixed here: https://github.com/Qiskit/qiskit-machine-learning/pull/432
When I ran your example on the main branch and passed `num_steps=10` to Pegasos I got the correct results. Let me know if you have questions.

**Comment by gcattan** [comment]
Thanks for the answer! I confirm it works as expected when using the development library (`git+https://github.com/Qiskit/qiskit-machine-learning#egg=qiskit_machine_learning`). Just have to wait for the next release then!
