### ISSUE TITLE
please is there a version of quantum gan with breast_canser.py dataset to reproduce it ?

### ISSUE THREAD

**Issue by BassantTolba1234** [Qiskit/qiskit-machine-learning#458]
### Environment

- **Qiskit Machine Learning version**:
- **Python version**: 
- **Operating system**: 

### What is happening?

i can not run quantum gan with breast_canser dataset

### How can we reproduce the issue?

run qgan with breast_cancer dataset

### What should happen?

i can not run quantum gan with breast_canser dataset

**Comment by adekusar-drl** [comment]
This is not a proper issue, but rather a question. 
Please post questions in the Qiskit slack workspace here: http://qiskit.slack.com, or on a quantum computing stackexchange: https://quantumcomputing.stackexchange.com/ or in another media. Thank you.
