### ISSUE TITLE
when I use my own dataset instead of breast_cancer.py dataset, I could not plot any scattering point in PCA plot as shown here. do you have any explanation /

### ISSUE THREAD

**Issue by BassantTolba1234** [Qiskit/qiskit-machine-learning#459]
### Environment

- **Qiskit Machine Learning version**:
- **Python version**: 
- **Operating system**: 

### What is happening?

when I use my own dataset instead of the breast_cancer.py dataset, I could not plot any scattering point in the PCA plot as shown here. do you have any explanation?
![image](https://user-images.githubusercontent.com/59363587/185380433-9cc9afdc-1ce8-48c2-8965-0882d84c9f42.png)

### How can we reproduce the issue?

run breast_cancer.py file with my own dataset

### What should happen?

the scattering plot of my dataset should appear as the breast_canser.py one as shown below
![image](https://user-images.githubusercontent.com/59363587/185380903-f3272159-c4ef-4779-a835-dc0f9d40ae13.png)

**Comment by adekusar-drl** [comment]
This is not a proper issue, but rather a question.
Please post questions in the Qiskit slack workspace here: http://qiskit.slack.com/, or on a quantum computing stackexchange: https://quantumcomputing.stackexchange.com/ or in another media. Thank you.
