### ISSUE TITLE
I have an error while running the file qgan.py. and I did not know the shape of dataset used in this file?

### ISSUE THREAD

**Issue by BassantTolba1234** [Qiskit/qiskit-machine-learning#460]
### Environment

- **Qiskit Machine Learning version**:
- **Python version**: 
- **Operating system**: 

### What is happening?

It appears error when I run the qgan.py file. It says that there is a missing data argument as shown below. I do not know what the data used is and its shape and dimension.

![image](https://user-images.githubusercontent.com/59363587/185401726-f6707e89-7975-4378-92ae-cdc8c274afba.png)

### How can we reproduce the issue?

by running the file qgan

### What should happen?

the loss of generator, discriminator and relative entropy should be printed

**Comment by adekusar-drl** [comment]
You have to pass the required parameter `data` to `QGAN`, please refer to the documentation: https://qiskit.org/documentation/machine-learning/stubs/qiskit_machine_learning.algorithms.QGAN.html#qiskit_machine_learning.algorithms.QGAN and to the QGAN tutorial: https://qiskit.org/documentation/machine-learning/tutorials/04_qgans_for_loading_random_distributions.html

**Comment by BassantTolba1234** [comment]
Thank you very much @adekusar-drl  for your comment. However, please can you share with me the suitable data I should pass to QGAN ? and what is the dimension of it please?
Thanks in advance.

**Comment by adekusar-drl** [comment]
In the QGAN tutorial a one dimensional array is used. Please take a look at it, I posted in the previous message.

**Comment by adekusar-drl** [comment]
I'm closing this issue as resolved.
