### ISSUE TITLE
Deprecate TorchRuntimeClient, corresponding classes, and the tutorial

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#472]
### What is the expected enhancement?

The `TorchRuntime` program does not use primitives, so it will be removed soon. Before that we have to deprecate everything that is related to `TorchRuntimeClient`. This includes:
- The runtime package with two scripts, `hookbase.py` and `torch_runtime_client.py`
- The tutorial `06_torch_runtime.ipynb`
- Other components if any

In case of the tutorial, I think, it is enough to add a text in bold in the beginning saying that the tutorial is deprecated, the corresponding runtime programs are deprecated and will be removed.

**Comment by adekusar-drl** [comment]
@manoelmarques Could you please take a look? Do we have an established practice in deprecating runtimes and tutorials?

**Comment by woodsp-ibm** [comment]
We do not publish tutorials using deprecated code - either they are updated to some new way, or they are removed if function is removed. Deprecated means users with existing code it will carry on working albeit emitting message - but as we discourage use of deprecated code we would not want a tutorial for new users to it.

**Comment by adekusar-drl** [comment]
OK, good to know, then it is even easier. We mark the code as deprecated and remove the tutorial.

**Comment by jyu00** [comment]
Based on the description, `TorchRuntimeClient` is going to be deprecated instead of updated to use the primitives, right? If so, can we shortened the deprecation period to say 1 month instead of the standard 3 months? The torch programs don't get a lot of usage, so the risk should be low.

**Comment by adekusar-drl** [comment]
@jyu00 I think, there is a common deprecation policy of 3 months. I'm not sure, I can change it.

**Comment by jyu00** [comment]
@1ucian0 do you think we can have an exception of a shorter deprecation time for this?

**Comment by woodsp-ibm** [comment]
Its a min of 3 months or two releases per current [Qiskit deprecation policy](https://qiskit.org/documentation/deprecation_policy.html#removing-a-feature) for  removal.

**Comment by NNCT2904** [comment]
Is there any plan for a runtime program to train neural network if this Torch runtime is deprecated?

**Comment by adekusar-drl** [comment]
@NNCT2904 Once primitive-based algorithms are out you should use `QiskitRuntimeService` to leverage primitives and runtimes.

**Comment by 1ucian0** [comment]
> Its a min of 3 months which has to include two releases per current [Qiskit deprecation policy](https://qiskit.org/documentation/deprecation_policy.html#removing-a-feature) for removal (item 3 there)

In principle, the depreciation policy applies to the module API (as the code included in the package), not to the service API. I would make sure qiskit-machine-learning code fails gracefully once the service is gone

**Comment by woodsp-ibm** [comment]
> I would make sure qiskit-machine-learning code fails gracefully once the service is gone

This code is just the front-end to the service - if the service goes away nothing works and the client code here is meaningless - if the service goes sooner this is essentially gone at the same time.

**Comment by manoelmarques** [comment]
So for a minimum deprecation time, I believe the msg would be something like:
```
....is deprecated as of version 0.5.0 and will be removed next release..."
```
That would be the shortest period unless a bug fix release is released just to remove it. Then the period could be 1 week, 3 days, one weekend :-) 
Another option is to just remove the code altogether and write in the release notes it has been removed. Since it is a service and not an api like mentioned above, the whole service is gone.
