### ISSUE TITLE
Migrate QGANs to new interfaces

### ISSUE THREAD

**Issue by stefan-woerner** [Qiskit/qiskit-machine-learning#48]
Migrate the currently existing QGAN implementation to the new NN interfaces in Qiskit ML:

- [ ] Introduce classical NN that implements NN interface
- [ ] Add "1 step" to optimizers (where possible, otherwise throw exception)
- [ ] Introduce QGAN that takes NN for generator (sampling) and discriminator (requires design first)
- [ ] Introduce required loss function (can we get gradients here without getting eval for all x?)

**Comment by adekusar-drl** [comment]
Closed via #414
