### ISSUE TITLE
Add a handy blueprint circuit that wraps feature map and ansatz circuits

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#505]
### What is the expected enhancement?

Sometimes it is handy to have a quantum circuit that wraps both feature map and ansatz. Such a circuit can be passed to quantum neural networks directly saving a few lines of code.

For example, now it is required to write:

```python
feature_map = ZZFeatureMap(num_inputs)
ansatz = RealAmplitudes(num_inputs)
qc = QuantumCircuit(num_inputs)
qc.compose(feature_map, inplace=True)
qc.compose(ansatz, inplace=True)

qnn = EstimatorQNN(
    circuit=qc,
    input_params=feature_map.parameters,
    weight_params=ansatz.parameters,
)
```

With a new, say, `QNNCircuit` we may reduce to:

```python
qnn_qc = QNNCircuit(num_inputs, ZZFeatureMap, RealAmplitudes)

qnn = EstimatorQNN(
    circuit=qnn_qc,
    input_params=qnn_qc.input_parameters,
    weight_params=qnn_qc.weight_parameters,
)
```

Such a circuit could be very handy in unit tests as well.

**Comment by realistix30** [comment]
Hi! I'd like to try this as my first issue.

**Comment by adekusar-drl** [comment]
Sure, give a try.

**Comment by adekusar-drl** [comment]
@realistix30 do you have any progress working on this issue?

**Comment by realistix30** [comment]
Hi,

Yes you can take over this one.
I got occupied reviewing for qiskit exam.

Thanks!

**Comment by adekusar-drl** [comment]
@GayatriVadaparty you can give a try.

**Comment by david-alber** [comment]
Hi,  

@GayatriVadaparty  any updates on the issue? 
If it is still available, I'd give it a shot (I'm a first timer as well...)  :) .

**Comment by adekusar-drl** [comment]
@GayatriVadaparty are there any updates?

**Comment by GayatriVadaparty** [comment]
Yeah i was busy since then… yeah you can givebit a shot!

**Comment by adekusar-drl** [comment]
@david-alber no assignees here :)

**Comment by david-alber** [comment]
@GayatriVadaparty cool thanks for the update.
@adekusar-drl I'm up to give it a try. Please assign me to the issue :)
