### ISSUE TITLE
N-dimensional output from QNN

### ISSUE THREAD

**Issue by anhphuong-ngo** [Qiskit/qiskit-machine-learning#562]
Hi everyone,

I am working on a hybrid CNN-QNN model. I am using codes from Qiskit tutorials, but the output dimension **1-dimensional**
Is there any way to have n-dimensional output (n>=2). I appreciate any ideas and suggestions. Thank you!

```python
#----------------------------------------------------------------------------------------------------------
#####Define and create QNN
def create_qnn():
    feature_map = ZZFeatureMap(2)
    ansatz = RealAmplitudes(2, reps=1)
    qc = QuantumCircuit(2)
    qc.compose(feature_map, inplace=True)
    qc.compose(ansatz, inplace=True)

    #### REMEMBER TO SET input_gradients=True FOR ENABLING HYBRID GRADIENT BACKPROP
    qnn = EstimatorQNN(
        circuit=qc,
        input_params=feature_map.parameters,
        weight_params=ansatz.parameters,
        input_gradients=True,
    )
    return qnn

qnn4 = create_qnn()

class Net(Module):
    def __init__(self, qnn):
        super().__init__()
        self.conv1 = Conv2d(1, 2, kernel_size=5)
        self.conv2 = Conv2d(2, 16, kernel_size=5)
        self.dropout = Dropout2d()
        self.fc1 = Linear(256, 64)
        self.fc2 = Linear(64, 2)  # 2-dimensional input to QNN
        self.qnn = TorchConnector(qnn)  # Apply torch connector, weights chosen
        # uniformly at random from interval [-1,1].
        self.fc3 = Linear(1, 1)  # **1-dimensional output from QNN**

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, 2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, 2)
        x = self.dropout(x)
        x = x.view(x.shape[0], -1)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        x = self.qnn(x)  # apply QNN
        x = self.fc3(x)
        return cat((x, 1 - x), -1)
```

**Comment by adekusar-drl** [comment]
@anhphuong-ngo Take a look here: https://qiskit.org/documentation/machine-learning/tutorials/01_neural_networks.html#5.1.-EstimatorQNN-with-Multiple-Observables

You may pass multiple observables to `EstimatorQNN` and get 2D-output like in this example:

```python
import numpy as np
from qiskit import QuantumCircuit
from qiskit.circuit.library import ZZFeatureMap, RealAmplitudes
from qiskit.quantum_info import SparsePauliOp

from qiskit_machine_learning.neural_networks import EstimatorQNN

fm = ZZFeatureMap(4)
ansatz = RealAmplitudes(4)
qc = QuantumCircuit(4)
qc.compose(fm, inplace=True)
qc.compose(ansatz, inplace=True)

obs1 = SparsePauliOp.from_list([("ZIII", 1)])
obs2 = SparsePauliOp.from_list([("IZII", 1)])
qnn = EstimatorQNN(circuit=qc, observables=[obs1, obs2], input_params=fm.parameters, weight_params=ansatz.parameters)
result = qnn.forward(np.random.random(fm.num_parameters), np.random.random(ansatz.num_parameters))
print(result)
```

Gives as output: `[[-0.23393417  0.22865092]]`

**Comment by anhphuong-ngo** [comment]
> @anhphuong-ngo Take a look here: https://qiskit.org/documentation/machine-learning/tutorials/01_neural_networks.html#5.1.-EstimatorQNN-with-Multiple-Observables
> 
> You may pass multiple observables to `EstimatorQNN` and get 2D-output like in this example:
> 
> ```python
> import numpy as np
> from qiskit import QuantumCircuit
> from qiskit.circuit.library import ZZFeatureMap, RealAmplitudes
> from qiskit.quantum_info import SparsePauliOp
> 
> from qiskit_machine_learning.neural_networks import EstimatorQNN
> 
> fm = ZZFeatureMap(4)
> ansatz = RealAmplitudes(4)
> qc = QuantumCircuit(4)
> qc.compose(fm, inplace=True)
> qc.compose(ansatz, inplace=True)
> 
> obs1 = SparsePauliOp.from_list([("ZIII", 1)])
> obs2 = SparsePauliOp.from_list([("IZII", 1)])
> qnn = EstimatorQNN(circuit=qc, observables=[obs1, obs2], input_params=fm.parameters, weight_params=ansatz.parameters)
> result = qnn.forward(np.random.random(fm.num_parameters), np.random.random(ansatz.num_parameters))
> print(result)
> ```
> 
> Gives as output: `[[-0.23393417 0.22865092]]`

Thank you for your good advice.
