### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Megatron9527** [Qiskit/qiskit-machine-learning#572]
### Environment

- **Qiskit Machine Learning version**:
- **Python version**: 
- **Operating system**: 
anyio                         3.6.2              
argon2-cffi                   21.3.0             
argon2-cffi-bindings          21.2.0             
asttokens                     2.2.1              
attrs                         22.2.0             
backcall                      0.2.0              
backports.functools-lru-cache 1.6.4              
beautifulsoup4                4.11.2             
bleach                        6.0.0              
certifi                       2022.12.7          
cffi                          1.14.0             
chardet                       3.0.4              
conda                         4.14.0             
conda-package-handling        1.7.0              
contourpy                     1.0.6              
cryptography                  2.9.2              
cycler                        0.11.0             
debugpy                       1.6.4              
decorator                     5.1.1              
defusedxml                    0.7.1              
dill                          0.3.5.1            
entrypoints                   0.4                
executing                     1.2.0              
fastdtw                       0.3.4              
fastjsonschema                2.16.3             
flit-core                     3.8.0              
fonttools                     4.38.0             
idna                          2.9                
importlib-metadata            6.0.0              
importlib-resources           5.12.0             
ipykernel                     6.17.1             
ipython                       8.7.0              
ipython-genutils              0.2.0              
ipywidgets                    8.0.2              
jedi                          0.18.2             
Jinja2                        3.1.2              
joblib                        1.2.0              
jsonschema                    4.17.3             
jupyter-client                7.4.7              
jupyter-core                  5.2.0              
jupyter-server                1.23.6             
jupyterlab-pygments           0.2.2              
jupyterlab-widgets            3.0.3              
kiwisolver                    1.4.4              
MarkupSafe                    2.1.1              
matplotlib                    3.6.2              
matplotlib-inline             0.1.6              
mistune                       2.0.5              
mpmath                        1.2.1              
nbclassic                     0.5.2              
nbclient                      0.7.2              
nbconvert                     7.2.9              
nbformat                      5.7.3              
nest-asyncio                  1.5.6              
notebook                      6.5.2              
notebook-shim                 0.2.2              
ntlm-auth                     1.5.0              
numpy                         1.23.5             
packaging                     23.0               
pandas                        1.5.2              
pandocfilters                 1.5.0              
parso                         0.8.3              
pbr                           5.11.0             
pexpect                       4.8.0              
pickleshare                   0.7.5              
Pillow                        9.3.0              
pip                           20.0.2             
pkgutil-resolve-name          1.3.10             
platformdirs                  3.1.0              
ply                           3.11               
prometheus-client             0.16.0             
prompt-toolkit                3.0.38             
psutil                        5.9.4              
ptyprocess                    0.7.0              
pure-eval                     0.2.2              
pycosat                       0.6.3              
pycparser                     2.20               
pydot                         1.4.2              
Pygments                      2.14.0             
pylatexenc                    2.10               
pyOpenSSL                     19.1.0             
pyparsing                     3.0.9              
pyrsistent                    0.18.0             
PySocks                       1.7.1              
python-dateutil               2.8.2              
pytz                          2022.6             
pyzmq                         24.0.1             
qiskit                        0.39.3             
qiskit-aer                    0.11.1             
qiskit-ibmq-provider          0.19.2             
qiskit-machine-learning       0.5.0              
qiskit-terra                  0.22.3             
requests                      2.23.0             
requests-ntlm                 1.1.0              
retworkx                      0.12.1             
ruamel-yaml                   0.15.87            
rustworkx                     0.12.1             
scikit-learn                  1.1.3              
scipy                         1.9.3              
seaborn                       0.12.1             
Send2Trash                    1.8.0              
setuptools                    46.4.0.post20200518
six                           1.14.0             
sklearn                       0.0.post1          
sniffio                       1.3.0              
soupsieve                     2.3.2.post1        
stack-data                    0.6.2              
stevedore                     4.1.1              
symengine                     0.9.2              
sympy                         1.11.1             
terminado                     0.15.0             
threadpoolctl                 3.1.0              
tinycss2                      1.2.1              
toolz                         0.12.0             
tornado                       6.2                
tqdm                          4.64.1             
traitlets                     5.9.0              
tweedledum                    1.1.1              
typing-extensions             4.4.0              
urllib3                       1.25.8             
wcwidth                       0.2.6              
webencodings                  0.5.1              
websocket-client              1.5.1              
websockets                    10.4               
wheel                         0.34.2             
widgetsnbextension            4.0.3              
zipp                          3.15.0 

### What is happening?

After the quantum circuit is successfully built, the error is reported in the QSVM model

### How can we reproduce the issue?

```python
from qiskit.primitives import Sampler
#from qiskit_machine_learning.kernels import FidelityQuantumKernel
from qiskit.algorithms.state_fidelities import ComputeUncompute
from qiskit.utils import QuantumInstance,algorithm_globals
from qiskit_machine_learning.kernels import QuantumKernel
from qiskit.circuit import QuantumCircuit,ParameterVector
from sklearn.preprocessing import label_binarize

#from tqdm import tqdm
#import sys
import qiskit

def gen_qasm():
    adhoc_dimension = 28
    num_qubits = 9
    iter = 1
    x = ParameterVector('x', length = 28)
    feature_map = QuantumCircuit(num_qubits)
    for _ in range(iter):
        for i in range(9):
            feature_map.h(i)
            feature_map.rx(x[i], i)


        for i in range(9):
            feature_map.h(i)
            feature_map.rx(x[9+i], i)

        for i in range(9):
            feature_map.h(i)
            feature_map.rx(x[18+i], i)

        feature_map.h(0)
        feature_map.rx(x[27],0)

    print(feature_map)
    #sys.exit(1)
    for i in range(1):
        seed = 42 + i
        algorithm_globals.random_seed = seed
    backend_options = {'max_parallel_threads':8}
    q_backend = QuantumInstance(Aer.get_backend('statevector_simulator'), shots=8192,backend_options=backend_options,seed_simulator=seed, seed_transpiler=seed)
    feature_map = ZZFeatureMap(feature_dimension = adhoc_dimension,reps = 2,entanglement = 'linear')
    sampler = Sampler()
    fidelity = ComputeUncompute(sampler = sampler)
    #q_kernel = FidelityQuantumKernel(fidelity = fidelity,feature_map = feature_map)
    q_kernel = QuantumKernel(feature_map=feature_map, quantum_instance=q_backend)
    print("11111111")
    return q_kernel

def loaddata(n, valid_rate = 0.4):

    data_list = []
    for i in range(n):
        data = pd.read_csv('/afs/ihep.ac.cn/users/d/dingb61/group/SVM/AllCSV/eeMC/sample_{}.csv'.format(i))
        data_list.append(data)


    df = pd.concat(data_list)
    df = shuffle(df)

    index = int(df.shape[0] * (1-valid_rate))
    train_data = df.iloc[:index]
    test_data = df.iloc[index:]

    train_data = train_data.iloc[0:400,]
    test_data = test_data.iloc[0:400,]
    train_label = train_data.pop('tag')
    test_label = test_data.pop('tag')

    return train_data, train_label, test_data, test_label

def trainSVM(train_data,train_label,test_data,test_label,q_kernel):
    svctrain = SVC(C =5,kernel = q_kernel.evaluate,probability=False)
    svctrain.fit(train_data,train_label)
    #print(svctrain)
    print("Model training completed")
    print("===========================================")
    #test_data = test_data.reset_index(drop=True)

    test_tag_pred = svctrain.predict(test_data)
    #test_tag_pred_data = pd.DataFrame({'tag':test_tag_pred})
    acc = metrics.accuracy_score(test_label,test_tag_pred)
    print("预测准确率accuracy：%f" %(acc))
    print("===========================================")
    my_confusion_matrix = confusion_matrix(test_label,test_tag_pred)
    print(my_confusion_matrix)

if __name__ == '__main__':
    q_kernel = gen_qasm()
    train_data, train_label, test_data, test_label = loaddata(2)
    trainSVM(train_data, train_label, test_data,test_label,q_kernel)
```

### What should happen?

CPU overload, unable to solve

**Comment by adekusar-drl** [comment]
The code is incomplete and does not reproduce the issue, no stack trace is given. Please correct the issue otherwise I close it as not planned.

**Comment by Megatron9527** [comment]
I am very glad to receive your email. The problem I submitted on github has been resolved due to incorrect parameter settings_ The map was overwritten after being repeatedly defined. Thank you for your attention. Best Wishes


| |
济南大学 丁彪
|
|
***@***.***
|
---- Replied Message ----
| From | Anton ***@***.***> |
| Date | 3/21/2023 17:37 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Qiskit/qiskit-machine-learning] Segmentation fault (core dumped) (Issue #572) |

@Megatron9527 Are there any new information on this issue?

**Comment by adekusar-drl** [comment]
Thanks for the update, I'm closing the issue.
