### ISSUE TITLE
Enhance SamplerQNN and EstimatorQNN with QNNCircuit

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#597]
### What should we add?

A newly introduced `QNNCircuit` should simplify interfaces of QNNs. Right now to create an QNN instance users have to pass at least three parameters: a circuit itself, a list of input parameters, and a list of trainable parameters or weights. With the new `QNNCircuit` the task should become easier to accomplish. Since the qnn circuit keeps track of feature map and ansatz, all circuit parameters are known as well. Therefore it is enough to pass an instance of `QNNCircuit` to a quantum neural network without passing lists of parameters. The networks should figure out the required lists of parameters themselves.

A user code should look like this:

```python
fm = ...
ansatz = ...
qc = QNNCircuit(feature_map=fm, ansatz=ansatz)
qnn = SamplerQNN(qc)
```

**Comment by david-alber** [comment]
Hey @adekusar-drl I'd love to pick up this one. Can you please assign me?
