### ISSUE TITLE
Fix `TorchConnector` problem with batching

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#60]
### Information

- **Qiskit Machine Learning version**: Latest release
- **Python version**: All 
- **Operating system**: all

### What is the current behavior?
Currently `TorchConnector` does not handle batches correctly. This should be improved.

**Comment by adekusar-drl** [comment]
@stefan-woerner Could you please take a look and provide more information on this issue? Would be nice to have steps to reproduce this issue.

**Comment by jonvet** [comment]
is this the same issue as #100 ?

**Comment by adekusar-drl** [comment]
Yes, must be the same. I have to double check one thing before I close this issue.

**Comment by adekusar-drl** [comment]
Fixed in #121.
