### ISSUE TITLE
Make `NeuralNetworkClassifier` to accept categorical input

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#62]
### What is the expected behavior?
Currently `NeuralNetworkClassifier` and `VQC` accepts only one hot encoding. Both classifiers should also accept categorical input.

**Comment by mattwright99** [comment]
@adekusar-drl I am interesting in picking up this ticket. Here is what I am thinking right now:
- Add a method to `NeuralNetworkClassifier` that checks for data of type string in each column and one-hot encode those columns.
- Call this method at the start of `fit`, `predict`, and `score`.

Alternatively, I could implement this function in the dataset_helper script so it can be used in other models.
What do you think?

**Comment by adekusar-drl** [comment]
Hi, in general you are right. So, first of all, please take a look at `OneHotEncoder` from sklearn, I hope we can make use of it instead of implementing a conversion login from scratch. Next, I'm not sure we need `categorical_cols` right away, we have a basic classifier that does not accept different type of labels, so should be easy to derive a label type from true labels.
Anyway, any suggestions are very welcome as some exploration is required here.

**Comment by mattwright99** [comment]
Oh I see, I thought you were refering to categorical features not labels. That should be easy enough to infer and transform. 
I will let you know if I have any other questions!

**Comment by adekusar-drl** [comment]
I don't know why I was thinking of labels only. Categorical features can be also a case, but such feature would require even more exploration and investigation. There's also `LabelEncoder` in sklearn that may help.

**Comment by mattwright99** [comment]
Ya categorical features would be interesting but slightly more complicated. I think we would either need to have the user preprocess the data before instantiating the model to specify number of qubits or we would have to use PCA to force the encoding dimensionality to fit the number of qubits. Could be a cool task but might warrant its own issue/PR.
And yes I have been looking into sklearn's `LabelEncoder` and `OneHotEncoder`. Thanks for the recommendation.

**Comment by mattwright99** [comment]
@adekusar-drl while we wrap this ticket up, I would be interested in exploring how to automatically handle categorical features, if you think that would be valuable.  Otherwise I would be happy finding another issue to take a look at.

Thoughts?

**Comment by adekusar-drl** [comment]
Certainly, you can explore categorical features, but, honestly, I don't know what you may hit on this road.
