### ISSUE TITLE
How to determine the required number of qubits for a VQC?

### ISSUE THREAD

**Issue by sri1905** [Qiskit/qiskit-machine-learning#632]
I am trying to understand the factors for determining the number of qubits.
   
1. I thought the number of qubits had to equal the number of classes because a class is interpreted from a bitstring. However, this [tutorial](https://qiskit.org/ecosystem/machine-learning/tutorials/02_neural_network_classifier_and_regressor.html#Multiple-classes-with-VQC) for multiclass classification uses only two qubits for a 3 class classification. Does it mean we can classify N classes with log(N) qubits? 
2. The number of features determines the number of qubits. However, I see two ways of increasing the number of parameters in the circuit to account for the features. We can increase the repetitions in the circuit, or we can increase the number of qubits. Is there a tradeoff? 

Thank you very much!

**Comment by adekusar-drl** [comment]
Hello,
1. The number of qubits does not relate directly to the number of classes. In case of VQC you the underlying QNN is `SamplerQNN` that maps a measured bit string to a class. For $N$ qubits we get a bit string of length $2^N$, thus, in theory, we can classify up to $2^N$ classes from a $N$-qubit circuit. So, answering your question, yes, that's right.
2. The number of features usually determine the number of qubits, but not necessarily. In case of rotation encoding, the number of qubits equals to the number of features. In case of amplitude encoding the number of qubits is $log(N)$, where $N$ is the number of features. But nothing prevents me to encode, say, 10 features into 5 or 6 qubits. You can increase the number of trainable parameters by increasing complexity of your ansatz, e.g. by increasing the number of repetitions. Increasing the number of qubits to increase the number of parameters is still possible, but may be not the best idea considering the limited number of qubits in real hardware. Tradeoff is very simple - design a model in the way that it requires a limited number of qubits and parameters and in the same time it produces good results. As usual, good metrics are the number of qubits and the depth of your circuit. Both of them is a limited resource.

Let me know if you have questions.

**Comment by sri1905** [comment]
Thank you, that helped!

I understand that first, I should try increasing the complexity of the circuit (more repetition) before increasing qubits to account for encoding more features. In the documentation for [Circuit library](https://qiskit.org/documentation/apidoc/circuit_library.html#n-local-circuits), there is some distinction between Data encoding circuits and N-local circuits. However, can use any of them for data encoding?

Also, unable to find RawFeatureVector, has it been deprecated? Is there an equivalent?

**Comment by sri1905** [comment]
My mistake, strange that the search result for RawFeatureVector was only the Reference page. Thank you!

**Comment by sri1905** [comment]
Yes, Thank you!
