### ISSUE TITLE
What is the backend for a VQC?

### ISSUE THREAD

**Issue by sri1905** [Qiskit/qiskit-machine-learning#633]
The parameter **quantum_instance** has been deprecated for a VQC (a backend was set using this parameter). Which backend is being used by default for VQC, and is there a way to still set it? Also, if a sampler is not set for a VQC, which QNN is used?

Thank you!

**Comment by adekusar-drl** [comment]
Hello, as stated in the documentation:

> If a sampler instance is sent, the underlying QNN will be of type [SamplerQNN](https://qiskit.org/ecosystem/machine-learning/stubs/qiskit_machine_learning.neural_networks.SamplerQNN.html#qiskit_machine_learning.neural_networks.SamplerQNN), and the sampler primitive will be used to compute the neural network’s results.

By default, an instance of `SamplerQNN` with the reference `Sampler` is created. It is still possible to pass a quantum instance and in this case a `CircuitQNN` instance will be created. Both `QuantumInstance` and `CircuitQNN` are deprecated in favor of the primitives(e.g. Sampler). You can manually create a sampler and pass to `VQC`, for instance, a runtime sampler to train a model on hardware.

**Comment by adekusar-drl** [comment]
As stated in the documentation:

> Run Options
>        shots (None or int) – The number of shots. If None, it calculates the probabilities. Otherwise, it samples from multinomial distributions.
>        seed (np.random.Generator or int) – Set a fixed seed or generator for the multinomial distribution. If shots is None, this option is ignored.

And options is a plain dictionary.

**Comment by sri1905** [comment]
Yes, I understood these options. I thought there were other options to help me configure the backend.

**Comment by adekusar-drl** [comment]
> Yes, I understood these options. I thought there were other options to help me configure the backend.

This is the reference Sampler, it does not have many parameters. Take a look at a recent blog post about primitives: https://medium.com/qiskit/what-are-qiskit-primitives-9bf63c1eacc7

**Comment by adekusar-drl** [comment]
Shall I close the issue?
