### ISSUE TITLE
TorchConnector forward pass unexpected behaviour

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/qiskit-machine-learning#644]
### Environment

- **Qiskit Machine Learning version**: `0.6.1`
- **Python version**: `3.10.11`
- **Operating system**: OSX

### What is happening?

I'm using `TorchConnector` with `SamplerQNN` and no interpret function, so I expect the output of `TorchConnector.forward` to be the same as `SamplerQNN.forward` (i.e. list of probabilities), but as a torch tensor.

Instead I get something that can't be a probability vector.

### How can we reproduce the issue?

Create a circuit with input parameter and weight parameter.

```python
from qiskit.circuit import QuantumCircuit, Parameter
from qiskit_machine_learning.connectors import TorchConnector
from qiskit_machine_learning.neural_networks import SamplerQNN
import numpy as np
import torch

input_ = Parameter('input')
weight = Parameter('weight')
qc = QuantumCircuit(1)
qc.rx(input_, 0)
qc.rz(weight, 0)

qc.draw('text')
```
```output
   ┌───────────┐┌────────────┐
q: ┤ Rx(input) ├┤ Rz(weight) ├
   └───────────┘└────────────┘
```

Then check it behaves as expected in `SamplerQNN`.

```python
sqnn = SamplerQNN(
        circuit=qc,
        input_params=[input_],
        weight_params=[weight]
    )
sqnn.forward(input_data=[0], weights=[np.pi])
```
```output
array([[1., 0.]])
```

Then put this inside a `TorchConnector` and run the forward pass.
```python
tc = TorchConnector(
    sqnn,
    initial_weights=[np.pi]
)

tc.forward(input_data=torch.tensor([0]))
```
```output
tensor([0, 0])
```

### What should happen?

I expect the output to be 
```
tensor([1, 0])
```

**Comment by adekusar-drl** [comment]
Fixed in the main branch.
