### ISSUE TITLE
Error in gradient calculation in qGAN using Gradient() 

### ISSUE THREAD

**Issue by bonavia1997** [Qiskit/qiskit-machine-learning#70]
### Information

- **Qiskit Machine Learning version**: 0.1.0 
- **Python version**: 3.8.8
- **Operating system**: Windows 10 

### What is the current behavior?

I was trying to apply "Phase shift rule" for gradient calculation in quantum GAN using the tutorial :
https://qiskit.org/documentation/tutorials/machine_learning/04_qgans_for_loading_random_distributions.html.

To do so, I replaced the line :
```python 
qgan.set_generator(generator_circuit=g_circuit, generator_init_params=init_params)
```
by
```python 
qgan.set_generator(generator_circuit=g_circuit, generator_init_params=init_params, generator_gradient = Gradient())
```
with `qiskit.aqua.operators.gradients.Gradient`.

However, while running 
```python 
result = qgan.run(quantum_instance)
```  
with ` reps = 2` (2 blocks in the quantum generator), the code shows me an error message below :

```bash
ValueError                                Traceback (most recent call last)
~\Anaconda3\lib\site-packages\qiskit\aqua\components\neural_networks\quantum_generator.py in loss(self, x, weights)
    382             # pylint: disable=no-member
--> 383             loss = (-1) * np.dot(np.log(x).transpose(), weights)
    384         except Exception:  # pylint: disable=broad-except
<__array_function__ internals> in dot(*args, **kwargs)
ValueError: shapes (4,1) and (6,4) not aligned: 1 (dim 1) != 6 (dim 0)
```

Please also find the full error message below 

 <img src="https://github.com/bonavia1997/datarep/blob/main/error_message.png?raw=true">.

### Steps to reproduce the problem
Please also find the code [here](https://github.com/bonavia1997/datarep/blob/main/qgan_phase_shift.ipynb). 

In the tutorial [04_qgans_for_loading_random_distributions.ipynb](https://qiskit.org/documentation/tutorials/machine_learning/04_qgans_for_loading_random_distributions.html),
 
1) Import gradient object :  
```python 
from qiskit.opflow import Gradient
```

2) Replace the line  :
```python 
qgan.set_generator(generator_circuit=g_circuit, generator_init_params=init_params)
```
by

```python  
qgan.set_generator(generator_circuit=g_circuit, generator_init_params=init_params, generator_gradient = Gradient())`
```

3)  Replace the line : 

```python
var_form = TwoLocal(int(np.sum(num_qubits)), 'ry', 'cz', entanglement=entangler_map, reps=1)
```

by 

```python
var_form = TwoLocal(int(np.sum(num_qubits)), 'ry', 'cz', entanglement=entangler_map, reps=2)
```

4) Add two more values for `init_params` (array of size 6) 

5) Run the quantum GAN. 

### What is the expected behavior?

By the chain rule, the gradient of the generator is calculated as : 
 
 <img src="https://render.githubusercontent.com/render/math?math=\frac{\partial L}{\partial \theta^i}= - \sum_j \frac{\partial p_j}{\partial \theta^i} \log(D(p_j))">.

(c.f. Appendix B in [Supplementary Information: Quantum Generative Adversarial Networks
for Learning and Loading Random Distributions](https://static-content.springer.com/esm/art%3A10.1038%2Fs41534-019-0223-2/MediaObjects/41534_2019_223_MOESM1_ESM.pdf))  

As we are summing over <img src="https://render.githubusercontent.com/render/math?math=p_j">, the matrix multiplication performed in 
```python 
loss_gradients = self.loss(prediction_generated, analytical_gradients).real
```
(line 411 in [quantum_machine_learning.algorithms.distribution_learners.qgan.quantum_generator](https://github.com/Qiskit/qiskit-machine-learning/blob/main/qiskit_machine_learning/algorithms/distribution_learners/qgan/quantum_generator.py#L411))
  
should take the form :

 <img src="https://render.githubusercontent.com/render/math?math=\frac{\partial L}{\partial \mathbf{\theta}}= - \log(D(\mathbf{p}))^T \underline{g}">

where 

<img src="https://render.githubusercontent.com/render/math?math=g_{i,j} = \frac{\partial p_i}{\partial \theta^j}">, 

However, 
```python 
analytical_gradients = np.array(grad_object.assign_parameters(value_dict).eval())
```
in 
```python 
def _convert_to_gradient_function(self, gradient_object, quantum_instance, discriminator)
```
currently returns: 

(line 410 in [quantum_machine_learning.algorithms.distribution_learners.qgan.quantum_generator](https://github.com/Qiskit/qiskit-machine-learning/blob/main/qiskit_machine_learning/algorithms/distribution_learners/qgan/quantum_generator.py#L410))
 
<img src="https://render.githubusercontent.com/render/math?math=g_{i,j} = \frac{\partial p_j}{\partial \theta^i}">, 

so the code returns an error for matrix multiplication. 

### Suggested solutions

I think the analytical gradients should be transposed : 

```python 
analytical_gradients = np.array(grad_object.assign_parameters(value_dict).eval())
```

to

```python 
analytical_gradients = np.transpose(np.array(grad_object.assign_parameters(value_dict).eval()))
```

**Comment by adekusar-drl** [comment]
Closed in #77
