### ISSUE TITLE
Create a UML diagram for VarQTE

### ISSUE THREAD

**Issue by dlasecki** [Qiskit/qiskit-machine-learning#71]

**Comment by dlasecki** [comment]
Issues to be covered in the design:
- [x] operator-based evolution (including Trotterization etc. 
- [x] variational time evolution using variational principles
- [ ] variational time evolution using "fitting"
- [x] case of non-Hermitian Hamiltonians
- [ ] case of time-dependent Hamiltonians

**Comment by Zoufalc** [comment]
McLachlan for time-dependent Hamiltonians follows the same principles as time-independent Hamiltonians. See Appendix  https://arxiv.org/pdf/1804.03023.pdf.

**Comment by adekusar-drl** [comment]
@dlasecki Shall I close the issue?

**Comment by dlasecki** [comment]
> @dlasecki Shall I close the issue?

@adekusar-drl Sorry, I forgot to reply. Yes, thanks for closing.
