### ISSUE TITLE
Verify `CircuitQNN` and `OpflowQNN` work correctly when no `QuantumInstance` is passed.

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#75]
### What is the expected enhancement?
The parameter `quantum_instance` in the `CircuitQNN` and `OpflowQNN` may have value of `None`. In such cases there should be additional checks:

- Add `if` statements to be sure code runs smoothly when no quantum instance is passes and it is not required at this moment.
- If the value is required, then raise an appropriate `QiskitMachineLearning` exception.
- Add getters/setters for quantum instance.

**Comment by stephenmurray2** [comment]
Hello @adekusar-drl 👋  I would be interested in creating a PR for this issue

**Comment by adekusar-drl** [comment]
Welcome! If you have questions, let me know!

**Comment by stephenmurray2** [comment]
Thanks! Still making sense of which logic should still get executed in the event of `NoneType` `quantum_instance` parameter, I will create a WIP PR shortly

**Comment by adekusar-drl** [comment]
Two hints (if I don't miss anything):
- `OpflowQNN` can run without a `qi`
- `CircuitQNN` needs a `qi` to run
I mean `forward` and `backward`. Other methods - depends.
