### ISSUE TITLE
Replace usage of the deprecated `StatevectorSimulator` with a new appropriate simulator in the unit tests

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#76]
### What is the expected enhancement?
Statevector simulator is deprecated now and use of this simulator generates a lot of deprecation warnings in the unit tests. This simulator must be replaced with a new version.

**Comment by woodsp-ibm** [comment]
In general, for the domains, there are quite a few deprecation or pendingdeprecation issues that need to be taken care of. I will note that the utils we had/have, that are now in Terra, for detecting if backend is statevector etc need revisiting too if we change use of Aer from the old way, I am not sure if these are used in the code anywhere here or not, but FYI in case.

**Comment by adekusar-drl** [comment]
Thanks for noting this. If I recall correctly, there are a few places where we have if statements like `if statevector: ...`. So, these are to be revised too.

**Comment by woodsp-ibm** [comment]
I was imagining we would update the util methods to accomodate the new backends so the checks still worked. But evidently things would need to be coordinated.

**Comment by manoelmarques** [comment]
I have it fixed but it depends on: Qiskit/qiskit-terra#6357
