### ISSUE TITLE
Introduce a parameter `input_gradients` to NeuralNetwork

### ISSUE THREAD

**Issue by adekusar-drl** [Qiskit/qiskit-machine-learning#90]
### What is the expected behavior?
As a feedback from #44,  we should add a parameter `input_gradients` to NeuralNetwork to expose it explicitly to users. By default it should be turned off. Also, we should not turn on input gradients explicitly in `TorchConnector` every time, turning on/off gradients is up a user via this new parameter.

**Comment by jonvet** [comment]
mind if I take a look at this one?

to confirm:
- `NeuralNetwork` and all classes that inherit from it should have a new parameter `input_gradients`
- should the current getter/setter in `NeuralNetwork` be deprecated?

**Comment by adekusar-drl** [comment]
I don't mind, any help is appreciated.

Things to do:

- Add `input_gradient` as a constructor parameter to `NeuralNetwork` with a default value of `False`. So, yes, this is the answer on the first question.
- Verify there are getter/setter in place (as I recall there's just a getter). So, no, current getter/setter are not deprecated.
- Remove a line in `TorchConnector` where `input_gradients` is set to `True` since this should be done explicitly by a user. Probably this should be mentioned in the documentation(docstrings).
- Add a line to set `input_gradients` to `True` in the torch connector tests.
- May be more unit tests are required, can't say now.
- Add a `reno` file with the changes.

Also take a look at https://github.com/Qiskit/qiskit-machine-learning/blob/main/CONTRIBUTING.md
Probably that's it. Let me know if you have questions.

**Comment by jonvet** [comment]
cool thanks, i also have permission from my employer now, so I'll get started
